### ISSUE TITLE
AttributeError: module 'skia' has no attribute 'PictureRecorder'

### ISSUE THREAD

**Issue by simplew2011** [0lru/p3ui#3]
AttributeError: module 'skia' has no attribute 'PictureRecorder'

**Comment by 0lru** [comment]
Workaround:
> pip install skia-python
@see: https://github.com/kyamagu/skia-python

(Todo: List skia-python in setup.py)

**Comment by 0lru** [comment]
Note: I Will try to use something like [skia-build](https://github.com/JetBrains/skia-build). That would also perform better without the need for Python/GIL in the render thread and it's usable from within C++. Downside: The executable will get larger.

**Comment by 0lru** [comment]
solved this, I think.
